---

- name: This is the main playbook which contains a play or multiple plays
  hosts: vsrx1  
  connection: local
  gather_facts: no
  
  vars_files:
    - vsrx_template_vars.yml
  
  tasks:
    - name: Generate config files
      template: 
        src: "vsrx_template.j2"
        dest: "./test.conf"
        
    - name: load config onto device
      junos_config:
        src: "test.conf"
        provider: "{{ credential }}"
